apiVersion: apps/v1
kind: Deployment
metadata:
  name: jivo-deploy
spec:
  replicas: 2
  selector:
   matchLabels:
    app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: front
          image: sane4ek/example:2
          ports:
          - containerPort: 80
        - name: back
          image: php:fpm-alpine